<?php
// AUTOMATICALLY GENERATED BY WRM CONFIGURATION SECTION, DO NOT CHANGE.
//     Use the WRM Configuration Section to change this value.

// Set armory http://www.wowarmory.com, http://eu.wowarmory.com,
// http://kr.wowarmory.com, or http://tw.wowarmory.com

define('ARMORY', 'http://www.wowarmory.com');
?>